### ISSUE TITLE
adapt to stateless modules in LaxarJS

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar-mocks#26]
The widget testing library uses some modules from LaxarJS tooling, that were stateful before `v2.0.0`. Since they will be stateless starting from `v2.0.0` usage needs to be adapted.
See LaxarJS/laxar#263.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

The LaxarJS Mocks library has been largely rewritten so that it does not need to perform dynamic module loading anymore. Also, it is now compatible to the LaxarJS v2.0 API and to the updated adapter API.

Because dynamic loading of the widget controller and descriptor is no longer an option, the `createSetupForWidget` method must have access to the artifacts listing as created by the LaxarJS webpack loader (`laxar-loader`).
The easiest way to achieve this is to configure your spec-tests (or spec-runners) to be loaded using the `laxar-mocks/spec-loader`.
